
export const GAME_CONSTANTS = {
  PLAYER_RADIUS: 14,
  PLAYER_ACCEL: 0.45,
  PLAYER_FRICTION: 0.96,
  PLAYER_MAX_VEL: 8,
  PLAYER_ROT_SPEED: 0.15,
  
  DASH_IMPULSE: 12,
  DASH_COOLDOWN_MS: 2000,
  DASH_DURATION_FRAMES: 10,

  BULLET_SPEED: 12,
  BULLET_COOLDOWN_MS: 300,
  BULLET_RADIUS: 4,
  BULLET_LIFE: 60,

  INITIAL_SPAWN_INTERVAL_MS: 1000,
  SPAWN_DECREMENT_INTERVAL_MS: 15000,
  SPAWN_DECREMENT_AMOUNT_MS: 100,
  MIN_SPAWN_INTERVAL_MS: 300,

  ASTEROID_MIN_RADIUS: 15,
  ASTEROID_MAX_RADIUS: 40,
  ASTEROID_MIN_SPEED: 1.5,
  ASTEROID_MAX_SPEED: 4,

  MONSTER_RADIUS: 18,
  MONSTER_INITIAL_SPEED: 1.2,
  MONSTER_SPEED_INC: 0.05, // Increase every level (15 seconds)
  MONSTER_KILL_SPEED_INC: 0.15, // Increase per individual monster killed
  MONSTER_SPAWN_START_MS: 8000,
  MONSTER_SPAWN_FAST_MS: 5000,
  MONSTER_MAX_COUNT: 5,
  MONSTER_ROT_SPEED: 0.04,

  POINTS_MONSTER: 50,
  POINTS_ASTEROID: 10,

  PARTICLE_COUNT: 25,
  PARTICLE_LIFE: 60,
  TRAIL_LIFE: 15,
  
  STAR_COUNT: 100,
  SCREEN_SHAKE_DURATION: 18, // frames at 60fps (~0.3s)
};
